[workspace]

members = [
    "felix-data",
    "felix-data/felix-collections",
    "felix-data/felix-datatypes",
    "felix-data/felix-test-utils",
    "felix-data/felix-computation-api",
    "felix-data/felix-export-api",
    "felix-data/felix-errors",

    "felix-gtk",
]
