pub const ACTIVITY_ID_COLUMN: i32 = 0;
pub const ACTIVITY_NAME_COLUMN: i32 = 1;

pub const ACTIVITY_GROUPS_NAME_COLUMN: i32 = 0;
pub const ACTIVITY_GROUPS_DELETE_COLUMN: i32 = 1;

pub const ACTIVITY_ENTITIES_NAME_COLUMN: i32 = 0;
pub const ACTIVITY_ENTITIES_DELETE_COLUMN: i32 = 1;
